
package publicador;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EdicionNoExisteExcep", targetNamespace = "http://publicador/")
public class EdicionNoExisteExcep_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EdicionNoExisteExcep faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EdicionNoExisteExcep_Exception(String message, EdicionNoExisteExcep faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EdicionNoExisteExcep_Exception(String message, EdicionNoExisteExcep faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicador.EdicionNoExisteExcep
     */
    public EdicionNoExisteExcep getFaultInfo() {
        return faultInfo;
    }

}
