
package publicador;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EvaluacionIncorrectaExcep", targetNamespace = "http://publicador/")
public class EvaluacionIncorrectaExcep_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EvaluacionIncorrectaExcep faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EvaluacionIncorrectaExcep_Exception(String message, EvaluacionIncorrectaExcep faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EvaluacionIncorrectaExcep_Exception(String message, EvaluacionIncorrectaExcep faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicador.EvaluacionIncorrectaExcep
     */
    public EvaluacionIncorrectaExcep getFaultInfo() {
        return faultInfo;
    }

}
