
package publicador;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UsuarioRepetidoExcep", targetNamespace = "http://publicador/")
public class UsuarioRepetidoExcep_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioRepetidoExcep faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioRepetidoExcep_Exception(String message, UsuarioRepetidoExcep faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UsuarioRepetidoExcep_Exception(String message, UsuarioRepetidoExcep faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicador.UsuarioRepetidoExcep
     */
    public UsuarioRepetidoExcep getFaultInfo() {
        return faultInfo;
    }

}
